on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    uses: carlthome/workflows/.github/workflows/nix.yaml@main
    with:
      cachix-cache: mirpkgs
      runs-on: ${{ matrix.os }}
      upload: false
    secrets:
      cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
