on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - id: set-matrix
        run: |
          set -Eeu
          matrix="$(nix eval --json '.#githubActions.matrix')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  build:
    needs: generate-build-matrix
    strategy:
      matrix: ${{fromJSON(needs.generate-build-matrix.outputs.matrix)}}
      fail-fast: false
    uses: carlthome/workflows/.github/workflows/nix.yaml@main
    with:
      attribute: ".#${{ matrix.attr }}"
      cachix-cache: mirpkgs
      runs-on: ${{ matrix.os }}
      upload: false
    secrets:
      cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
