on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    uses: carlthome/workflows/.github/workflows/nix.yaml@main
    with:
      cachix-cache: carlthome
      runs-on: ${{ matrix.os }}
    secrets:
      cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
